apiVersion: v1
data:
  init-influxdb.sh: "#!/bin/bash\nset -e\n\nAUTH_ENABLED=\"$INFLUXDB_HTTP_AUTH_ENABLED\"\n\nif
    [ -z \"$AUTH_ENABLED\" ]; then\n\tAUTH_ENABLED=\"$(grep -iE '^\\s*auth-enabled\\s*=\\s*true'
    /etc/influxdb/influxdb.conf | grep -io 'true' | cat)\"\nelse\n\tAUTH_ENABLED=\"$(echo
    \"$INFLUXDB_HTTP_AUTH_ENABLED\" | grep -io 'true' | cat)\"\nfi\n\nINIT_USERS=$([
    ! -z \"$AUTH_ENABLED\" ] && [ ! -z \"$INFLUXDB_ADMIN_USER\" ] && echo 1 || echo)\n\n#
    Check if an environment variable for where to put meta is set.\n# If so, then
    use that directory, otherwise use the default.\nif [ -z \"$INFLUXDB_META_DIR\"
    ]; then\n\tMETA_DIR=\"/var/lib/influxdb/meta\"\nelse\n\tMETA_DIR=\"$INFLUXDB_META_DIR\"\nfi\n\nif
    ( [ ! -z \"$INIT_USERS\" ] || [ ! -z \"$INFLUXDB_DB\" ] || [ \"$(ls -A /docker-entrypoint-initdb.d
    2> /dev/null)\" ] ) && [ ! \"$(ls -d \"$META_DIR\" 2>/dev/null)\" ]; then\n\n\tINIT_QUERY=\"\"\n\tCREATE_DB_QUERY=\"CREATE
    DATABASE $INFLUXDB_DB\"\n\n\tif [ ! -z \"$INIT_USERS\" ]; then\n\n\t\tif [ -z
    \"$INFLUXDB_ADMIN_PASSWORD\" ]; then\n\t\t\tINFLUXDB_ADMIN_PASSWORD=\"$(< /dev/urandom
    tr -dc _A-Z-a-z-0-9 | head -c32;echo;)\"\n\t\t\techo \"INFLUXDB_ADMIN_PASSWORD:$INFLUXDB_ADMIN_PASSWORD\"\n\t\tfi\n\n\t\tINIT_QUERY=\"CREATE
    USER \\\"$INFLUXDB_ADMIN_USER\\\" WITH PASSWORD '$INFLUXDB_ADMIN_PASSWORD' WITH
    ALL PRIVILEGES\"\n\telif [ ! -z \"$INFLUXDB_DB\" ]; then\n\t\tINIT_QUERY=\"$CREATE_DB_QUERY\"\n\telse\n\t\tINIT_QUERY=\"SHOW
    DATABASES\"\n\tfi\n\n\tINFLUXDB_INIT_PORT=\"8086\"\n\n\tINFLUXDB_HTTP_BIND_ADDRESS=127.0.0.1:$INFLUXDB_INIT_PORT
    INFLUXDB_HTTP_HTTPS_ENABLED=true influxd \"$@\" &\n\n\tpid=\"$!\"\n\n\tINFLUX_CMD=\"influx
    -host 127.0.0.1 -port $INFLUXDB_INIT_PORT -ssl -unsafeSsl -execute \"\n\n\tfor
    i in {30..0}; do\n\t\tif $INFLUX_CMD \"$INIT_QUERY\" &> /dev/null; then\n\t\t\tbreak\n\t\tfi\n\t\techo
    'influxdb init process in progress...'\n\t\tsleep 1\n\tdone\n\n\tif [ \"$i\" =
    0 ]; then\n\t\techo >&2 'influxdb init process failed.'\n\t\texit 1\n\tfi\n\n\tif
    [ ! -z \"$INIT_USERS\" ]; then\n\n\t\tINFLUX_CMD=\"influx -host 127.0.0.1 -port
    $INFLUXDB_INIT_PORT -ssl -unsafeSsl -username ${INFLUXDB_ADMIN_USER} -password
    ${INFLUXDB_ADMIN_PASSWORD} -execute \"\n\n\t\tif [ ! -z \"$INFLUXDB_DB\" ]; then\n\t\t\t$INFLUX_CMD
    \"$CREATE_DB_QUERY\"\n\t\tfi\n\n\t\tif [ ! -z \"$INFLUXDB_USER\" ] && [ -z \"$INFLUXDB_USER_PASSWORD\"
    ]; then\n\t\t\tINFLUXDB_USER_PASSWORD=\"$(< /dev/urandom tr -dc _A-Z-a-z-0-9 |
    head -c32;echo;)\"\n\t\t\techo \"INFLUXDB_USER_PASSWORD:$INFLUXDB_USER_PASSWORD\"\n\t\tfi\n\n\t\tif
    [ ! -z \"$INFLUXDB_USER\" ]; then\n\t\t\t$INFLUX_CMD \"CREATE USER \\\"$INFLUXDB_USER\\\"
    WITH PASSWORD '$INFLUXDB_USER_PASSWORD'\"\n\n\t\t\t$INFLUX_CMD \"REVOKE ALL PRIVILEGES
    FROM \\\"$INFLUXDB_USER\\\"\"\n\n\t\t\tif [ ! -z \"$INFLUXDB_DB\" ]; then\n\t\t\t\t$INFLUX_CMD
    \"GRANT ALL ON \\\"$INFLUXDB_DB\\\" TO \\\"$INFLUXDB_USER\\\"\"\n\t\t\tfi\n\t\tfi\n\n\t\tif
    [ ! -z \"$INFLUXDB_WRITE_USER\" ] && [ -z \"$INFLUXDB_WRITE_USER_PASSWORD\" ];
    then\n\t\t\tINFLUXDB_WRITE_USER_PASSWORD=\"$(< /dev/urandom tr -dc _A-Z-a-z-0-9
    | head -c32;echo;)\"\n\t\t\techo \"INFLUXDB_WRITE_USER_PASSWORD:$INFLUXDB_WRITE_USER_PASSWORD\"\n\t\tfi\n\n\t\tif
    [ ! -z \"$INFLUXDB_WRITE_USER\" ]; then\n\t\t\t$INFLUX_CMD \"CREATE USER \\\"$INFLUXDB_WRITE_USER\\\"
    WITH PASSWORD '$INFLUXDB_WRITE_USER_PASSWORD'\"\n\t\t\t$INFLUX_CMD \"REVOKE ALL
    PRIVILEGES FROM \\\"$INFLUXDB_WRITE_USER\\\"\"\n\n\t\t\tif [ ! -z \"$INFLUXDB_DB\"
    ]; then\n\t\t\t\t$INFLUX_CMD \"GRANT WRITE ON \\\"$INFLUXDB_DB\\\" TO \\\"$INFLUXDB_WRITE_USER\\\"\"\n\t\t\tfi\n\t\tfi\n\n\t\tif
    [ ! -z \"$INFLUXDB_READ_USER\" ] && [ -z \"$INFLUXDB_READ_USER_PASSWORD\" ]; then\n\t\t\tINFLUXDB_READ_USER_PASSWORD=\"$(<
    /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32;echo;)\"\n\t\t\techo \"INFLUXDB_READ_USER_PASSWORD:$INFLUXDB_READ_USER_PASSWORD\"\n\t\tfi\n\n\t\tif
    [ ! -z \"$INFLUXDB_READ_USER\" ]; then\n\t\t\t$INFLUX_CMD \"CREATE USER \\\"$INFLUXDB_READ_USER\\\"
    WITH PASSWORD '$INFLUXDB_READ_USER_PASSWORD'\"\n\t\t\t$INFLUX_CMD \"REVOKE ALL
    PRIVILEGES FROM \\\"$INFLUXDB_READ_USER\\\"\"\n\n\t\t\tif [ ! -z \"$INFLUXDB_DB\"
    ]; then\n\t\t\t\t$INFLUX_CMD \"GRANT READ ON \\\"$INFLUXDB_DB\\\" TO \\\"$INFLUXDB_READ_USER\\\"\"\n\t\t\tfi\n\t\tfi\n\n\tfi\n\n\tfor
    f in /docker-entrypoint-initdb.d/*; do\n\t\tcase \"$f\" in\n\t\t\t*.sh)     echo
    \"$0: running $f\"; . \"$f\" ;;\n\t\t\t*.iql)    echo \"$0: running $f\"; $INFLUX_CMD
    \"$(cat \"\"$f\"\")\"; echo ;;\n\t\t\t*)        echo \"$0: ignoring $f\" ;;\n\t\tesac\n\t\techo\n\tdone\n\n\tif
    ! kill -s TERM \"$pid\" || ! wait \"$pid\"; then\n\t\techo >&2 'influxdb init
    process failed. (Could not stop influxdb)'\n\t\texit 1\n\tfi\n\nfi\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: influxdb-init-script
