apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
status:
  loadBalancer: {}
