apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: openshift-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccount: grafana-sa
      serviceAccountName: grafana-sa
      containers:
      - image: nexus.openshift.training:8090/grafana/grafana:9.2.10
        name: grafana
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault          
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: GF_DATABASE_WAL
          value: "true"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-data
          - mountPath: /usr/share/grafana/conf/defaults.ini
            name: grafana-config
            subPath: defaults.ini
            readOnly: true
          - name: grafana-certificate
            readOnly: true
            mountPath: "/usr/share/grafana/certificates"
        resources:
          limits:
            cpu: 2
            memory: 4G
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-certificate
          secret:
            secretName: grafana-certificate
        - name: grafana-config
          configMap:
            name: grafana-config
        
