apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: python-get-metrics
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: python-get-metrics
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: fmk.nexus-ci.onefiserv.net/vendor/redhat/get-ocp-metrics-by-api:v1.0
            name: python-get-metrics
            resources:
              limits:
                cpu: 200m
                memory: 400Mi
            env:
            - name: CLUSTER_NAME
              value: zopomint
            - name: API_ENDPOINT
              value: api.zopomint.ocpz.fiserv.one
            - name: INFLUXDB_ENDPOINT
              value: influxdb.apps.zopomint.ocpz.fiserv.one
          restartPolicy: OnFailure
          serviceAccountName: python-cluster-view
          serviceAccount: python-cluster-view
  schedule: '* * * * *'
status: {}
